"use client";

import { useState, useEffect, useCallback } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";

interface PlanTask {
  id: string;
  stepNumber: number;
  title: string;
  description: string;
  status: string;
  assignedTo?: string;
  assignedType?: string;
  dependsOn?: number[];
  result?: string;
  startedAt?: string;
  endedAt?: string;
  createdAt: string;
}

interface Plan {
  id: string;
  goal: string;
  status: string;
  userId: string;
  userName?: string;
  createdAt: string;
  updatedAt?: string;
  reasoning?: string;
  estimatedDurationMinutes?: number;
  steps?: string[];
  tasks?: PlanTask[];
  autoGenerated?: boolean;
  workflowId?: string;
  runId?: string;
  approvedBy?: string;
  approvedByName?: string;
  rejectedBy?: string;
  rejectionReason?: string;
}

const API = "/api/v1";

function getToken(): string {
  return typeof window !== "undefined" ? localStorage.getItem("agentos_token") ?? "" : "";
}

async function apiFetch<T>(path: string, opts?: RequestInit): Promise<T> {
  const res = await fetch(`${API}${path}`, {
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${getToken()}`,
      ...(opts?.headers ?? {}),
    },
    ...opts,
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.detail ?? `HTTP ${res.status}`);
  }
  const json = await res.json();
  return (json.data ?? json) as T;
}

const TASK_STATUS_CONFIG: Record<string, { icon: string; color: string; bg: string }> = {
  pending:  { icon: "○", color: "text-slate-400", bg: "bg-slate-800" },
  running:  { icon: "◑", color: "text-blue-400",  bg: "bg-blue-950/40" },
  complete: { icon: "●", color: "text-emerald-400", bg: "bg-emerald-950/40" },
  failed:   { icon: "✗", color: "text-red-400",   bg: "bg-red-950/40" },
  skipped:  { icon: "–", color: "text-slate-600",  bg: "bg-slate-900" },
};

const PLAN_STATUS_STYLES: Record<string, string> = {
  draft: "bg-slate-700 text-slate-200",
  planning: "bg-blue-800 text-blue-200",
  approved: "bg-emerald-800 text-emerald-200",
  executing: "bg-amber-800 text-amber-200",
  complete: "bg-emerald-900 text-emerald-300",
  failed: "bg-red-900 text-red-300",
  rejected: "bg-red-800 text-red-300",
};

export default function PlanDetailPage() {
  const params = useParams();
  const router = useRouter(); // eslint-disable-line @typescript-eslint/no-unused-vars
  const planId = params?.id as string;

  const [plan, setPlan] = useState<Plan | null>(null);
  const [tasks, setTasks] = useState<PlanTask[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [actionLoading, setActionLoading] = useState<"approve" | "reject" | null>(null);
  const [rejectReason, setRejectReason] = useState("");
  const [showReject, setShowReject] = useState(false);

  const load = useCallback(async () => {
    try {
      const data = await apiFetch<Plan & { tasks?: PlanTask[] }>(`/plans/${planId}`);
      setPlan(data);
      setTasks(data.tasks ?? []);
      setError(null);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Failed to load plan");
    } finally {
      setLoading(false);
    }
  }, [planId]);

  useEffect(() => {
    if (planId) {
      load();
      const id = setInterval(load, 5000);
      return () => clearInterval(id);
    }
  }, [planId, load]);

  const handleApprove = async () => {
    setActionLoading("approve");
    try {
      await apiFetch(`/plans/${planId}/approve`, { method: "POST" });
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Approval failed");
    } finally {
      setActionLoading(null);
    }
  };

  const handleReject = async () => {
    setActionLoading("reject");
    try {
      await apiFetch(`/plans/${planId}/reject`, {
        method: "POST",
        body: JSON.stringify({ reason: rejectReason }),
      });
      setShowReject(false);
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Rejection failed");
    } finally {
      setActionLoading(null);
    }
  };

  const completedTasks = tasks.filter((t) => t.status === "complete").length;
  const progressPct = tasks.length > 0 ? Math.round((completedTasks / tasks.length) * 100) : 0;

  if (loading) return (
    <div className="min-h-screen bg-[#0d0f14] flex items-center justify-center text-slate-500">Loading plan…</div>
  );

  if (error && !plan) return (
    <div className="min-h-screen bg-[#0d0f14] flex items-center justify-center">
      <div className="text-red-400 text-sm">{error}</div>
    </div>
  );

  if (!plan) return null;

  const canAct = plan.status === "draft" || plan.status === "planning";

  return (
    <div className="min-h-screen bg-[#0d0f14] text-slate-100">
      <div className="max-w-4xl mx-auto px-4 py-8">
        {/* Breadcrumb */}
        <div className="flex items-center gap-2 text-sm text-slate-500 mb-6">
          <Link href="/plans" className="hover:text-slate-300 transition-colors">Plans</Link>
          <span>/</span>
          <span className="font-mono text-slate-400">{plan.id.slice(0, 8)}…</span>
        </div>

        {/* Plan header */}
        <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 mb-6">
          <div className="flex items-start justify-between gap-4 mb-4">
            <div className="flex-1">
              <div className="flex items-center gap-2 mb-2">
                <span className={`text-xs px-2.5 py-0.5 rounded-full font-medium ${PLAN_STATUS_STYLES[plan.status] ?? "bg-slate-700 text-slate-200"}`}>
                  {plan.status}
                </span>
                {plan.autoGenerated && (
                  <span className="text-xs px-2 py-0.5 rounded-full bg-blue-900/50 text-blue-400 border border-blue-800/50">
                    auto-generated
                  </span>
                )}
              </div>
              <h1 className="text-xl font-bold text-white leading-snug">{plan.goal}</h1>
            </div>
            {canAct && (
              <div className="flex gap-2 shrink-0">
                <button
                  onClick={handleApprove}
                  disabled={actionLoading !== null}
                  className="px-4 py-2 bg-emerald-800 hover:bg-emerald-700 disabled:opacity-40 text-emerald-100 text-sm font-semibold rounded-xl transition-colors"
                >
                  {actionLoading === "approve" ? "…" : "✓ Approve"}
                </button>
                <button
                  onClick={() => setShowReject(true)}
                  disabled={actionLoading !== null}
                  className="px-4 py-2 bg-red-900 hover:bg-red-800 disabled:opacity-40 text-red-200 text-sm font-semibold rounded-xl transition-colors"
                >
                  ✗ Reject
                </button>
              </div>
            )}
          </div>

          {/* Metadata grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
            {[
              ["Created", new Date(plan.createdAt).toLocaleString()],
              ["By", plan.userName || plan.userId],
              ["Est. Duration", plan.estimatedDurationMinutes ? `${plan.estimatedDurationMinutes}m` : "—"],
              ["Tasks", `${completedTasks}/${tasks.length} done`],
            ].map(([label, value]) => (
              <div key={label} className="bg-slate-800/60 rounded-lg p-2.5">
                <div className="text-slate-500">{label}</div>
                <div className="text-slate-200 mt-0.5 font-medium">{value}</div>
              </div>
            ))}
          </div>

          {/* Reasoning */}
          {plan.reasoning && (
            <div className="mt-4 bg-slate-800/40 rounded-lg p-3 text-xs text-slate-400 border-l-2 border-violet-700">
              <span className="text-violet-400 font-medium">Reasoning: </span>{plan.reasoning}
            </div>
          )}

          {/* Progress bar */}
          {tasks.length > 0 && (
            <div className="mt-4">
              <div className="flex items-center justify-between text-xs text-slate-500 mb-1">
                <span>Progress</span>
                <span>{progressPct}%</span>
              </div>
              <div className="h-2 bg-slate-800 rounded-full overflow-hidden">
                <div
                  className="h-full bg-emerald-600 rounded-full transition-all duration-500"
                  style={{ width: `${progressPct}%` }}
                />
              </div>
            </div>
          )}
        </div>

        {/* Reject modal */}
        {showReject && (
          <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50">
            <div className="bg-[#161b27] border border-slate-700 rounded-2xl p-6 w-full max-w-md mx-4">
              <h3 className="text-lg font-bold text-white mb-3">Reject Plan</h3>
              <textarea
                className="w-full bg-slate-900 border border-slate-700 rounded-xl p-3 text-sm text-slate-100 resize-none focus:outline-none focus:border-red-600"
                rows={3}
                placeholder="Reason for rejection (optional)…"
                value={rejectReason}
                onChange={(e) => setRejectReason(e.target.value)}
                autoFocus
              />
              <div className="flex gap-3 mt-4">
                <button onClick={() => setShowReject(false)} className="flex-1 py-2 rounded-xl bg-slate-800 text-slate-300 text-sm hover:bg-slate-700">Cancel</button>
                <button onClick={handleReject} disabled={actionLoading !== null} className="flex-1 py-2 rounded-xl bg-red-900 hover:bg-red-800 disabled:opacity-40 text-red-200 text-sm font-semibold">
                  {actionLoading === "reject" ? "…" : "Confirm Reject"}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Error */}
        {error && <div className="bg-red-950/50 border border-red-800 rounded-xl p-3 text-sm text-red-300 mb-4">{error}</div>}

        {/* Tasks */}
        <div>
          <h2 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-3">
            Execution Steps ({tasks.length})
          </h2>
          {tasks.length === 0 ? (
            <div className="text-slate-500 text-sm">No tasks defined for this plan.</div>
          ) : (
            <div className="space-y-2">
              {tasks.map((task, idx) => {
                const cfg = TASK_STATUS_CONFIG[task.status] ?? TASK_STATUS_CONFIG.pending;
                return (
                  <div key={task.id} className={`rounded-xl border p-4 transition-all ${cfg.bg} ${task.status === "running" ? "border-blue-700" : "border-slate-800"}`}>
                    <div className="flex items-start gap-3">
                      {/* Step number + connector */}
                      <div className="flex flex-col items-center shrink-0">
                        <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold border ${task.status === "complete" ? "bg-emerald-800 border-emerald-600 text-emerald-200" : task.status === "running" ? "bg-blue-800 border-blue-600 text-blue-200 animate-pulse" : task.status === "failed" ? "bg-red-900 border-red-700 text-red-300" : "bg-slate-800 border-slate-600 text-slate-400"}`}>
                          {task.status === "complete" ? "✓" : task.status === "failed" ? "✗" : task.stepNumber}
                        </div>
                        {idx < tasks.length - 1 && (
                          <div className={`w-px flex-1 mt-1 min-h-[16px] ${task.status === "complete" ? "bg-emerald-800" : "bg-slate-800"}`} />
                        )}
                      </div>

                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between gap-2">
                          <span className="text-sm font-semibold text-white">{task.title}</span>
                          <span className={`text-xs ${cfg.color}`}>{cfg.icon} {task.status}</span>
                        </div>
                        {task.description && (
                          <p className="text-xs text-slate-500 mt-0.5">{task.description}</p>
                        )}
                        {task.assignedTo && (
                          <div className="mt-1.5 flex items-center gap-1.5">
                            <span className="text-xs text-slate-600">→</span>
                            <span className="text-xs bg-slate-800 text-slate-400 px-2 py-0.5 rounded-full border border-slate-700 font-mono">
                              {task.assignedType ?? "agent"}: {task.assignedTo.slice(0, 8)}…
                            </span>
                          </div>
                        )}
                        {task.result && (
                          <div className="mt-2 bg-slate-900 rounded-lg p-2 text-xs text-slate-300 font-mono border border-slate-700">
                            {task.result}
                          </div>
                        )}
                        {task.dependsOn && task.dependsOn.length > 0 && (
                          <div className="mt-1 text-xs text-slate-600">
                            Depends on step{task.dependsOn.length > 1 ? "s" : ""}: {task.dependsOn.join(", ")}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Workflow link */}
        {plan.workflowId && (
          <div className="mt-6 pt-4 border-t border-slate-800">
            <Link
              href={`/observability`}
              className="text-xs text-slate-500 hover:text-violet-400 transition-colors"
            >
              → View in Observability (workflow: {plan.workflowId.slice(0, 8)}…)
            </Link>
          </div>
        )}
      </div>
    </div>
  );
}
