"use client";

import { useState, useEffect, useCallback } from "react";
import Link from "next/link";

interface PlanTask {
  id: string;
  stepNumber: number;
  title: string;
  status: string;
}

interface Plan {
  id: string;
  goal: string;
  status: string;
  userId: string;
  userName?: string;
  createdAt: string;
  reasoning?: string;
  estimatedDurationMinutes?: number;
  steps?: string[];
  tasks?: PlanTask[];
  autoGenerated?: boolean;
  workflowId?: string;
}

const API = "/api/v1";

function getToken(): string {
  return typeof window !== "undefined" ? localStorage.getItem("agentos_token") ?? "" : "";
}

async function apiFetch<T>(path: string, opts?: RequestInit): Promise<T> {
  const res = await fetch(`${API}${path}`, {
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${getToken()}`,
      ...(opts?.headers ?? {}),
    },
    ...opts,
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.detail ?? `HTTP ${res.status}`);
  }
  const json = await res.json();
  return (json.data ?? json) as T;
}

const STATUS_STYLES: Record<string, string> = {
  draft: "bg-slate-700 text-slate-200",
  planning: "bg-blue-800 text-blue-200",
  approved: "bg-emerald-800 text-emerald-200",
  executing: "bg-amber-800 text-amber-200",
  complete: "bg-emerald-900 text-emerald-300",
  failed: "bg-red-900 text-red-300",
  rejected: "bg-red-800 text-red-300",
};

const TASK_STATUS_ICON: Record<string, string> = {
  pending: "○",
  running: "◑",
  complete: "●",
  failed: "✗",
  skipped: "–",
};

export default function PlansPage() {
  const [plans, setPlans] = useState<Plan[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [statusFilter, setStatusFilter] = useState("");
  const [creating, setCreating] = useState(false);
  const [newGoal, setNewGoal] = useState("");
  const [submitting, setSubmitting] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const q = statusFilter ? `?plan_status=${statusFilter}` : "";
      const data = await apiFetch<Plan[]>(`/plans${q}`);
      setPlans(data);
      setError(null);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Failed to load plans");
    } finally {
      setLoading(false);
    }
  }, [statusFilter]);

  useEffect(() => { load(); const id = setInterval(load, 15000); return () => clearInterval(id); }, [load]);

  const handleCreate = async () => {
    if (!newGoal.trim() || submitting) return;
    setSubmitting(true);
    try {
      await apiFetch("/plans", { method: "POST", body: JSON.stringify({ goal: newGoal.trim() }) });
      setNewGoal("");
      setCreating(false);
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Failed to create plan");
    } finally {
      setSubmitting(false);
    }
  };

  const statusCounts = plans.reduce((acc: Record<string, number>, p) => {
    acc[p.status] = (acc[p.status] || 0) + 1;
    return acc;
  }, {});

  return (
    <div className="min-h-screen bg-[#0d0f14] text-slate-100">
      <div className="max-w-6xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-700 to-purple-900 flex items-center justify-center text-xl">🗺️</div>
            <div>
              <h1 className="text-2xl font-bold text-white tracking-tight">Supervisor Plans</h1>
              <p className="text-sm text-slate-400">Goal decomposition → ordered task execution</p>
            </div>
          </div>
          <button
            onClick={() => setCreating(true)}
            className="px-4 py-2 bg-violet-700 hover:bg-violet-600 text-white text-sm font-semibold rounded-xl transition-colors"
          >
            + New Plan
          </button>
        </div>

        {/* Stats bar */}
        <div className="grid grid-cols-5 gap-2 mb-6">
          {Object.entries(STATUS_STYLES).slice(0, 5).map(([st]) => (
            <button
              key={st}
              onClick={() => setStatusFilter(statusFilter === st ? "" : st)}
              className={`rounded-xl border p-3 text-center transition-all ${statusFilter === st ? "border-violet-500 bg-violet-950/40" : "border-slate-800 bg-slate-900/60 hover:border-slate-600"}`}
            >
              <div className={`text-lg font-bold ${(STATUS_STYLES[st] ?? "").split(" ")[1]}`}>{statusCounts[st] ?? 0}</div>
              <div className="text-xs text-slate-500 capitalize mt-0.5">{st}</div>
            </button>
          ))}
        </div>

        {/* Create modal */}
        {creating && (
          <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50">
            <div className="bg-[#161b27] border border-slate-700 rounded-2xl p-6 w-full max-w-lg mx-4">
              <h2 className="text-lg font-bold text-white mb-4">Create New Plan</h2>
              <textarea
                className="w-full bg-slate-900 border border-slate-700 rounded-xl p-3 text-sm text-slate-100 resize-none focus:outline-none focus:border-violet-500"
                rows={4}
                placeholder="Describe your goal — the supervisor will decompose it into tasks automatically…"
                value={newGoal}
                onChange={(e) => setNewGoal(e.target.value)}
                autoFocus
              />
              <div className="flex gap-3 mt-4">
                <button onClick={() => setCreating(false)} className="flex-1 py-2 rounded-xl bg-slate-800 text-slate-300 text-sm hover:bg-slate-700 transition-colors">Cancel</button>
                <button
                  onClick={handleCreate}
                  disabled={!newGoal.trim() || submitting}
                  className="flex-1 py-2 rounded-xl bg-violet-700 hover:bg-violet-600 disabled:opacity-40 text-white text-sm font-semibold transition-colors"
                >
                  {submitting ? "Creating…" : "Create Plan"}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Error */}
        {error && <div className="bg-red-950/50 border border-red-800 rounded-xl p-4 text-sm text-red-300 mb-4">{error}</div>}

        {/* Plans list */}
        {loading && plans.length === 0 ? (
          <div className="text-slate-500 text-sm">Loading plans…</div>
        ) : plans.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 text-center">
            <span className="text-5xl mb-4">🗺️</span>
            <p className="text-slate-400">No plans yet.</p>
            <p className="text-slate-600 text-sm mt-1">Start a chat or create a plan manually.</p>
          </div>
        ) : (
          <div className="space-y-3">
            {plans.map((plan) => (
              <Link
                key={plan.id}
                href={`/plans/${plan.id}`}
                className="block rounded-2xl border border-slate-800 bg-slate-900/60 hover:border-slate-600 hover:bg-slate-900 transition-all p-5"
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1.5">
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${STATUS_STYLES[plan.status] ?? "bg-slate-700 text-slate-200"}`}>
                        {plan.status}
                      </span>
                      {plan.autoGenerated && (
                        <span className="text-xs px-2 py-0.5 rounded-full bg-blue-900/50 text-blue-400 border border-blue-800/50">auto</span>
                      )}
                      <span className="text-xs text-slate-600 font-mono">{plan.id.slice(0, 8)}…</span>
                    </div>
                    <p className="text-white font-medium truncate">{plan.goal}</p>
                    {plan.reasoning && (
                      <p className="text-xs text-slate-500 mt-1 truncate">{plan.reasoning}</p>
                    )}
                  </div>
                  <div className="shrink-0 text-right">
                    <div className="text-xs text-slate-500">{new Date(plan.createdAt).toLocaleDateString()}</div>
                    {plan.estimatedDurationMinutes && (
                      <div className="text-xs text-slate-600 mt-0.5">~{plan.estimatedDurationMinutes}m</div>
                    )}
                  </div>
                </div>

                {/* Step pills */}
                {plan.steps && plan.steps.length > 0 && (
                  <div className="flex gap-1.5 mt-3 flex-wrap">
                    {plan.steps.map((step, i) => (
                      <span key={i} className="text-xs bg-slate-800 text-slate-400 px-2 py-0.5 rounded-full border border-slate-700">
                        {i + 1}. {step}
                      </span>
                    ))}
                  </div>
                )}
              </Link>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
